services:
   database:
      container_name: "postgres-database-development"
      image: "postgres:16.0-alpine3.18"
      env_file:
         - ../.env.development
      ports:
         - "13546:5432"
